name: Build & Publish Debug APK

on:
 push:
  branches:
   - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v2

      - name: java
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 16.x

      - name: cordova
        run: npm install -g cordova

      - name: angularCli
        run: npm install -g @angular/cli
        
      - name: Ionic
        run: npm install -g @ionic/cli
      
      - name: npm
        run: npm install
        
      - name: Remove Android platform
        run: ionic cordova platform rm android
        
      - name: Add Android platform
        run: ionic cordova platform add android@latest

      - name: Build Android Dev APK
        run: ionic cordova build android
      
      - name: git 
        run: |
         git config --global user.name "tonysoprano02"
         git config --global user.email "antonivroman88@gmail.com"
         
         git add platforms/android/app/build/outputs/apk/debug/app-debug.apk -f
         git commit -m "add apk file"
         git push
         
      - name: add code
        working-directory: ./platforms/android/app/
        run: echo 'android {buildTypes {release{crunchPngs false}}}' >> build.gradle

      - name: gradlew clean
        working-directory: ./platforms/android/
        run: ./gradlew clean

      - name: Build Android Release APK
        run: ionic cordova build android --release
        
      - name: Generate the Android App Bundle
        working-directory: ./platforms/android/
        run: ./gradlew bundle

#       - name: aab file
#         run: |
#          git config --global user.name "tonysoprano02"
#          git config --global user.email "antonivroman88@gmail.com"

#          git add platforms/android/app/build/outputs/bundle/release/app-release.aab -f
#          git commit -m "add aab file"
#          git push
         
      - name: certificate
        run: keytool -genkey -v -keystore myapp.keystore -alias myapp -keypasswd  -keyalg RSA -keysize 2048 -validity 10000 -storetype jks && zxcsdfkjsdkjgdfgdsdfg
      # - name: Upload dev APK
      #   uses: actions/upload-artifact@v1
      #   with:
      #     name: app-dev
      #     path: platforms/android/app/build/outputs/apk/debug/app-debug.apk

      # - name: Upload release bundle
      #   uses: actions/upload-artifact@v1
      #   with:
      #     name: app-release
      #     path: platforms/android/app/build/outputs/bundle/release/app.aab

